

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/secondhand_db
spring.datasource.username=postgres
spring.datasource.password=Pattin16
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.web.resources.static-locations=file:./frontend/,classpath:/static/
spring.web.resources.static-locations=file:///D:/javaProjects/second-hand-web/frontend/,classpath:/static/
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

cloudinary.cloud-name=qbmuoow7
cloudinary.api-key=313652428928678
cloudinary.api-secret=2exSK58hjW385YTduZRzRCJVi9A

spring.application.name=REVERB-TEST